# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/giovanni/anaconda3/envs/vgtenv/bin/cmake

# The command to remove a file.
RM = /home/giovanni/anaconda3/envs/vgtenv/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/giovanni/Downloads/supplementary/rvde-code

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/giovanni/Downloads/supplementary/rvde-code

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/giovanni/anaconda3/envs/vgtenv/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/giovanni/anaconda3/envs/vgtenv/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/giovanni/Downloads/supplementary/rvde-code/CMakeFiles /home/giovanni/Downloads/supplementary/rvde-code//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/giovanni/Downloads/supplementary/rvde-code/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cnpy

# Build rule for target.
cnpy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cnpy
.PHONY : cnpy

# fast build rule for target.
cnpy/fast:
	$(MAKE) $(MAKESILENT) -f libs/cnpy/CMakeFiles/cnpy.dir/build.make libs/cnpy/CMakeFiles/cnpy.dir/build
.PHONY : cnpy/fast

#=============================================================================
# Target rules for targets named libclew

# Build rule for target.
libclew: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libclew
.PHONY : libclew

# fast build rule for target.
libclew/fast:
	$(MAKE) $(MAKESILENT) -f libs/clew/CMakeFiles/libclew.dir/build.make libs/clew/CMakeFiles/libclew.dir/build
.PHONY : libclew/fast

#=============================================================================
# Target rules for targets named libgpu

# Build rule for target.
libgpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libgpu
.PHONY : libgpu

# fast build rule for target.
libgpu/fast:
	$(MAKE) $(MAKESILENT) -f libs/gpu/CMakeFiles/libgpu.dir/build.make libs/gpu/CMakeFiles/libgpu.dir/build
.PHONY : libgpu/fast

#=============================================================================
# Target rules for targets named hexdumparray

# Build rule for target.
hexdumparray: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hexdumparray
.PHONY : hexdumparray

# fast build rule for target.
hexdumparray/fast:
	$(MAKE) $(MAKESILENT) -f libs/gpu/CMakeFiles/hexdumparray.dir/build.make libs/gpu/CMakeFiles/hexdumparray.dir/build
.PHONY : hexdumparray/fast

#=============================================================================
# Target rules for targets named vgt

# Build rule for target.
vgt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vgt
.PHONY : vgt

# fast build rule for target.
vgt/fast:
	$(MAKE) $(MAKESILENT) -f vgt/CMakeFiles/vgt.dir/build.make vgt/CMakeFiles/vgt.dir/build
.PHONY : vgt/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cnpy"
	@echo "... hexdumparray"
	@echo "... libclew"
	@echo "... libgpu"
	@echo "... vgt"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

